// react-app/src/App.js
import React, { useEffect, useState } from 'react'
import CharacterList from './components/CharacterList'
import data from "./components/data"
const App = ( {props} ) => {
  
  const [chars, setChars] = useState([])
  console.log("toggle value ....",props)
  useEffect(() => {

let url=`https://rickandmortyapi.com/api/character/?name=${props.artistName}`;

fetch(url)
.then((response) => response.json())
  .then((data) =>{ 
    console.log("fiieieiei",data)
    setChars(data.results)})
.catch((err) => console.error(`Fetch problem: ${err.message}`));
    
  
  }, [props.artistName])
  
  let lang = ['Java', 'DotNet', 'Python'];
    let filtervalue = props.selectedvalue;
    let toggleval = props.toggleval == 'true';
    let newArray = filtervalue && filtervalue !== "0" ? lang.filter(item => item === filtervalue ) :lang
    return (
      <>
      <CharacterList chars={chars} />
       <div class="card">
   
  <div class="card-header">
    React Application
  </div>
  <div class="card-body">
  <ul class="list-group list-group-flush">
  {
    newArray.map((value,index)=>{
      return <li class="list-group-item" key={index}>{value}</li>
    })
  }
  </ul>
  </div>
  <div class="card-body">
  <div class='row'>
  <div class="col-6">
    <button type="button" id="reactincrementer" class="btn btn-outline-secondary">Increment Counter</button>
    </div>
    <div class="col-6">
    {
      toggleval && 
      <span class="badge badge-info">Called from angular app!!!</span>
    }
            </div>
    </div>
</div>
</div>
      </>
  
    )
}

export default App

// angular-app/src/app/app.component.ts
import { Component, OnInit, Input, OnChanges, SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnChanges {
  @Input() trackname:string;
  @Input() selectedvalue: string;
  newArray: any[];
  charArray: any[];
  filtervalue: string;
  lang: any[];
  ngOnInit() {
    this.lang = ['Java', 'DotNet', 'Python'];
    this.newArray = this.selectedvalue && this.selectedvalue !== '0' ? this.lang.filter(item => item === this.selectedvalue ) : this.lang;
    this.charArray=[];

  }

  ngOnChanges(changes: SimpleChanges) {

    let url=`https://rickandmortyapi.com/api/location/?name=${changes.trackname.currentValue}`;

fetch(url)
.then((response) => response.json())
  .then((data) =>{ 
    this.charArray=data.results;
    console.log("fron angular dta",data)
  })
.catch((err) => console.error(`Fetch problem: ${err.message}`));


    console.log("changes  from react to angular ..",changes.trackname)
    if (changes.selectedvalue.currentValue !== changes.selectedvalue.previousValue) {
      const curr = changes.selectedvalue.currentValue;
      this.newArray = curr && curr !== '0' ? this.lang.filter(item => item === curr ) : this.lang;
    }
  }
}

<div class="card">
     <div class="card-header">
  Search for Episodes By Id
  </div>
  <div class="card-body">
  <ul class="list_location" >
    <li  *ngFor="let val of charArray"  class="card_location"  >  
      {{val.name}}   
    <div class="dimension">
      {{val.dimension}}   
    </div> 
    
    <div class="dimension">
      {{val.type}}   
    </div> 
    </li>
  </ul>
  </div>
  <div class="card-body">
  <button type="button" id="angularincrementer" class="btn btn-outline-secondary">Increment Counter</button>
  <button type="button" id="toggleme" style="float:right" class="btn btn-info">Toggle</button>
  </div>

 
</div>
